spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coupon_example
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

#logging:
#  level:
#    org.springframework.transaction.interceptor: TRACE
#    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
#    org.hibernate.resource.transaction: DEBUG
#    org.hibernate.SQL: DEBUG

